[features]
seeds = false
skip-lint = false
[programs.localnet]
lupo = "8FaDrHMnbmGYcatRTqtnEtYqtRP5F7cKpEhFHqk3maiY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/eleonorademenna/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
