[features]
seeds = false
skip-lint = false
[programs.devnet]
lupo = "8FaDrHMnbmGYcatRTqtnEtYqtRP5F7cKpEhFHqk3maiY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./DLgPUECQ6QNh6WKNXNFq9smUTYvTDVjwgUMttxvR87pN.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
